# Database Image with Slurm
FROM docker pull ghcr.io/logicalisuki/slurm-containers/slurm-base:latest

# Install MariaDB server and client
RUN apt-get update && apt-get install -y \
    mariadb-server \
    mariadb-client && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Expose ports for MariaDB and slurmdbd
EXPOSE 3306 6819

# Start MariaDB and slurmdbd
CMD ["bash", "-c", "mysqld_safe & sleep 5 && slurmdbd"]
