# Worker Image
FROM ubiquitycluster/slurm-base:latest

# Install SSH Server and Kerberos Client
RUN apt-get update && apt-get install -y \
    python3 \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Ensure Munge is set up
RUN chown munge:munge /etc/munge/munge.key && chmod 400 /etc/munge/munge.key

RUN rm -rf /etc/localtime && ln -sf /usr/share/zoneinfo/Europe/London /etc/localtime

RUN pip3 install --include-deps easybuild ensurepath

# Expose slurm port
EXPOSE 6818

# Start command
#CMD ["bash", "-c","cp /tmp/munge.key /etc/munge/ && munged --force && \
#                   sssd -d 6 --logger=files && slurmd -D -v -f /etc/slurm/slurm.conf"]
CMD ["bash", "-c", "cp /tmp/munge.key /etc/munge/ && \
                    chown munge:munge /etc/munge/munge.key && \
                    chmod 400 /etc/munge/munge.key && \
                    munged --force && \
                    sssd -d 6 --logger=files & \
                    slurmd -D -v -f /etc/slurm/slurm.conf"]
