# Database Image with Slurm
FROM ubiquitycluster/slurm-base:latest

RUN mkdir -p /usr/local/slurm/etc/

# Ensure Munge is set up
RUN chown munge:munge /etc/munge/munge.key && chmod 400 /etc/munge/munge.key


# Expose ports for MariaDB and slurmdbd
EXPOSE 3306 6819

# Start MariaDB and slurmdbd
CMD ["bash", "-c", "cp /tmp/munge.key /etc/munge/ && munged --force && cp /tmp/slurmdbd.conf /usr/local/slurm/etc/slurmdbd.conf && chmod 600 /usr/local/slurm/etc/slurmdbd.conf && chown slurm:slurm /usr/local/slurm/etc/slurmdbd.conf  && slurmdbd -D -v"]
