# Login Image
FROM ubiquitycluster/slurm-base:latest

# Install SSH Server and Kerberos Client
RUN apt-get update && apt-get install -y \
    pip \
    pipx \
    libpam-modules \
    libpam-modules-bin \
    openssh-server \
    krb5-user \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set Timezone
RUN rm -rf /etc/localtime && ln -sf /usr/share/zoneinfo/Europe/London /etc/localtime

# Set Kerberos Credential Cache Path
RUN export KRB5CCNAME=/tmp/krb5cc_$(id -u)

# Install Easy Build
RUN pipx install --include-deps easybuild ensurepath

# Ensure Munge is set up
RUN chown munge:munge /etc/munge/munge.key && chmod 400 /etc/munge/munge.key

# Expose Port 22 and 6817 for slurm for login
EXPOSE 22 88 389 636 3268 6817

# Start command
CMD ["bash", "-c", "\
    cp /tmp/munge.key /etc/munge/ && \
    chown munge:munge /etc/munge/munge.key && chmod 400 /etc/munge/munge.key && \
    munged --force && \
    cp /etc/slurm/slurm.conf /usr/local/slurm/etc && \
    mkdir -p /run/sshd && \
    /usr/sbin/sshd -D & \
    sssd -d 6 --logger=files & \
    sleep infinity"]
