# Worker Image
FROM ubiquitycluster/slurm-base:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN sed -i 's|http://archive.ubuntu.com|https://archive.ubuntu.com|g' /etc/apt/sources.list

# Enable all Ubuntu repos
RUN apt-get update && \
    apt-get install -y software-properties-common ca-certificates && \
    add-apt-repository universe && \
    add-apt-repository multiverse && \
    add-apt-repository restricted && \
    apt-get update


# Install SSH Server, Python3-pip, Python3-venv, and pipx
RUN apt-get update && apt-get install -y \
        libnss-wrapper \
        munge \ 
        libmunge2 \
        libmunge-dev \
        python3-pip \
        python3-venv \
        libpam-modules \
        libpam-modules-bin \
        openssh-server \
        krb5-user \
        man \
        manpages \
        manpages-dev \
        emacs-nox \
        less \
        groff \
        locales \
        nano \
        vim-tiny \
        mc \
        lua5.3 \
        lmod \
        htop \
        btop \
        iotop \
        tmux && \
        locale-gen en_GB.UTF-8 && \
        update-locale LANG=en_GB.UTF-8 && \
        apt-get clean && \
        rm -rf /var/lib/apt/lists/*

# Updating locales so that man pages dont look weird
ENV LANG en_GB.UTF-8
ENV LANGUAGE en_GB:en
ENV LC_ALL en_GB.UTF-8


# Updating envs for LD_PRELOAD
ENV LD_PRELOAD=/lib/x86_64-linux-gnu/libnss_wrapper.so
ENV NSS_WRAPPER_PASSWD=/mnt/identity-store/global.passwd
ENV NSS_WRAPPER_GROUP=/mnt/identity-store/global.group

# Create a Virtual Environment for Python packages
RUN python3 -m venv /opt/venv

# Upgrade pip inside the virtual environment and install pipx
RUN /opt/venv/bin/pip install --upgrade pip

# Install EasyBuild using pipx inside the virtual environment
RUN /opt/venv/bin/pip install EasyBuild

# Ensure Munge is set up
RUN chown munge:munge /etc/munge/munge.key && chmod 400 /etc/munge/munge.key

# Set Timezone
RUN rm -rf /etc/localtime && ln -sf /usr/share/zoneinfo/Europe/London /etc/localtime

# Expose slurm port
EXPOSE 6818

# Add virtual environment to PATH
ENV PATH="/opt/venv/bin:/usr/local/slurm/bin:$PATH"

# Source Lmod initialization script and add to PATH
RUN echo "source /usr/share/lmod/lmod/init/bash" >> ~/.bashrc

# Start command
CMD ["bash", "-c", "cp /tmp/munge.key /etc/munge/ && \
                    chown munge:munge /etc/munge/munge.key && \
                    chmod 400 /etc/munge/munge.key && \
                    munged --force && \
                    sssd -d 6 --logger=files & \
                    slurmd -D -v -f /etc/slurm/slurm.conf"]
