# Controller Image
FROM ubiquitycluster/slurm-base:latest

# Additional dependencies for the controller
RUN apt-get update && apt-get install -y \
    libmunge2 \
    munge && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Ensure Munge is set up
RUN chown munge:munge /etc/munge/munge.key && chmod 400 /etc/munge/munge.key

# Start command
CMD ["slurmctld"]
