# Controller Image
FROM ubiquitycluster/slurm-base:latest

# Ensure Munge is set up
RUN chown munge:munge /etc/munge/munge.key && chmod 400 /etc/munge/munge.key

# RUN useradd -ms /bin/bash slurm
RUN mkdir -p /var/log/slurm

EXPOSE 6817

# Start command
CMD ["sh", "-c", "cp /tmp/munge.key /etc/munge/ && munged --force && chown slurm:slurm /var/spool/slurmctld && mkdir /var/spool/slurm && cp /secrets/slurm/jwt_hs256.key /var/spool/slurm/jwt_hs256.key && slurmctld -D -v -f /etc/slurm/slurm.conf"]
