# Controller Image
FROM ubiquitycluster/slurm-base:latest

RUN rm -rf /etc/localtime && ln -sf /usr/share/zoneinfo/Europe/London /etc/localtime

# Ensure Munge is set up
RUN chown munge:munge /etc/munge/munge.key && chmod 400 /etc/munge/munge.key

# Expose necessary ports
EXPOSE 6817 6820

# Start command
CMD ["sh", "-c", "\
    mkdir -p /etc/munge && \
    cp /tmp/munge.key /etc/munge/ && \
    chown munge:munge /etc/munge/munge.key && chmod 400 /etc/munge/munge.key && \
    munged --force && \
    touch /var/spool/slurm/jwt_hs256.key && \
    chown -R slurm:slurm /var/spool/slurmctld && \
    export SLURM_CONF=/etc/slurm/slurm.conf && \
    export SLURM_JWT=daemon && \
    slurmctld -D -v -f $SLURM_CONF \
"]
