# Worker Image
FROM ubiquitycluster/slurm-base:latest

# Ensure Munge is set up
RUN chown munge:munge /etc/munge/munge.key && chmod 400 /etc/munge/munge.key

# Expose Port 22 and 6817 for slurm for login
EXPOSE 22 6817

# Start command
CMD ["bash", "-c","munged --force && cp /etc/slurm/slurm.conf /usr/local/slurm/etc/slurm.conf && sleep infinity"]

