# Worker Image
FROM ubiquitycluster/slurm-base:latest


# Ensure Munge is set up
RUN chown munge:munge /etc/munge/munge.key && chmod 400 /etc/munge/munge.key

# Expose slurm port
EXPOSE 6818

# Start command
CMD ["bash", "-c","munged --force && slurmd -D -v -f /etc/slurm/slurm.conf"]

