name: Docker Publish (DockerHub + GHCR)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]

env:
  DOCKERHUB_REGISTRY: docker.io
  GHCR_REGISTRY: ghcr.io
  DOCKERHUB_USERNAME: ubiquitycluster
  DOCKERHUB_PAT: ${{ secrets.DOCKER_PAT }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      ####################
      # DockerHub Login
      ####################
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKERHUB_REGISTRY }}
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PAT }}

      ####################
      # GHCR Login
      ####################
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      ####################
      # Shared build template (base, controller, etc.)
      ####################

      - name: Build and push all images
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.DOCKERHUB_REGISTRY }}/${{ env.DOCKERHUB_USERNAME }}/slurm-base:latest
            ${{ env.GHCR_REGISTRY }}/${{ github.repository }}/slurm-base:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push controller
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile-controller
          push: true
          tags: |
            ${{ env.DOCKERHUB_REGISTRY }}/${{ env.DOCKERHUB_USERNAME }}/slurm-controller:latest
            ${{ env.GHCR_REGISTRY }}/${{ github.repository }}/slurm-controller:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push database
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile-database
          push: true
          tags: |
            ${{ env.DOCKERHUB_REGISTRY }}/${{ env.DOCKERHUB_USERNAME }}/slurm-database:latest
            ${{ env.GHCR_REGISTRY }}/${{ github.repository }}/slurm-database:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push worker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile-worker
          push: true
          tags: |
            ${{ env.DOCKERHUB_REGISTRY }}/${{ env.DOCKERHUB_USERNAME }}/slurm-worker:latest
            ${{ env.GHCR_REGISTRY }}/${{ github.repository }}/slurm-worker:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push login
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile-login
          push: true
          tags: |
            ${{ env.DOCKERHUB_REGISTRY }}/${{ env.DOCKERHUB_USERNAME }}/slurm-login:latest
            ${{ env.GHCR_REGISTRY }}/${{ github.repository }}/slurm-login:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push adcli
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile-adcli
          push: true
          tags: |
            ${{ env.DOCKERHUB_REGISTRY }}/${{ env.DOCKERHUB_USERNAME }}/slurm-adcli:latest
            ${{ env.GHCR_REGISTRY }}/${{ github.repository }}/slurm-adcli:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

